// week4/frontend/src/components/PollResults.vue
<template>
  <div class="poll-results">
    <h3>Poll Results</h3>
    <div v-for="(option, index) in poll.options" :key="index" class="result-item">
      <span class="result-label">{{ option }}</span>
      <div class="result-bar">
        <div class="result-bar-fill" :style="{ width: getPercent(index) + '%' }"></div>
        <span class="result-percent">{{ getPercent(index) }}%</span>
      </div>
    </div>
  </div>
</template>

<script>
import api from '../services/api';

export default {
  data() {
    return {
      poll: {
        question: '',
        options: [],
        votes: []
      }
    };
  },
  async created() {
    const response = await api.getPoll();
    this.poll = response.data;
  },
  methods: {
    getPercent(index) {
      const totalVotes = this.poll.votes.reduce((sum, v) => sum + v, 0);
      return totalVotes > 0 ? ((this.poll.votes[index] / totalVotes) * 100).toFixed(1) : 0;
    }
  }
};
</script>

<style>
/* Add styles for the poll results */
.poll-results {
  margin-top: 20px;
}
.result-item {
  margin-bottom: 15px;
}
.result-label {
  font-weight: bold;
  margin-bottom: 4px;
  display: block;
}
.result-bar {
  background: #eee;
  border-radius: 4px;
  overflow: hidden;
  height: 24px;
  position: relative;
}
.result-bar-fill {
  background: #007acc;
  height: 100%;
  transition: width 1s ease-out;
  border-radius: 4px 0 0 4px;
}
.result-percent {
  position: absolute;
  right: 10px;
  top: 0;
  height: 100%;
  line-height: 24px;
  color: #fff;
  font-weight: bold;
}
</style>

// polling-system-react-week7/src/components/PollResults.jsx
import React from 'react';

function PollResults({ poll }) {
  const totalVotes = poll.votes.reduce((sum, v) => sum + v, 0);
  return (
    <div>
      <h2>Poll Results</h2>
      {poll.options.map((option, index) => {
        const count = poll.votes[index];
        const percent = totalVotes ? ((count / totalVotes) * 100).toFixed(1) : 0;
        return (
          <div key={index} style={{ marginBottom: '1rem' }}>
            <strong>{option}:</strong> {count} vote(s) – {percent}%
            <div style={{
              background: '#eee',
              borderRadius: '4px',
              overflow: 'hidden',
              marginTop: '0.3rem'
            }}>
              <div style={{
                width: `${percent}%`,
                background: '#007acc',
                height: '1rem'
              }} />
            </div>
          </div>
        );
      })}
      <p>Total Votes: {totalVotes}</p>
    </div>
  );
}

export default PollResults;
